In [6]:
import numpy as np
import matplotlib.pyplot as plt


# Defining some baseline functions 
# Pauli Matrices
X = np.array([
    [0,1],
    [1,0]
])
Y = np.array([
    [0,0+-1j],
    [0+1j,0]
])
Z = np.array([
    [1,0],
    [0,-1]
])
I = np.eye(2)

# useful construction matrices
outerO = np.array([
    [1,0],
    [0,0]
])
outer1 = np.array([
    [0,0],
    [0,1]
])

# Encoding gates
Cx = np.kron(outerO,I)+np.kron(outer1,X)
Cz = np.kron(outerO,I)+np.kron(outer1,Z)
H = 1/np.sqrt(2)*np.array([
    [1,1],
    [1,-1]
])
S = np.array([
    [1,0],
    [0,0+1j]
])

Cx,Cz


(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]]),
 array([[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0., -1.]]))

In [160]:
sigma = [X,Z,I,X@Z,Z@X]
sigmaLabels = ['X','Z','I','XZ','ZX']
# Remember that they're all their own inverses
# So I don't need to repeat myself


# I need to make a function which given some operator O, 
# will return what combination of the pauli matrices and kron it is
def conjugate(O):
    for i in range(len(sigma)):
        for j in range(len(sigma)):
            newOperator = np.kron(sigma[i],sigma[j])
            combination = O@np.linalg.inv(newOperator) -np.eye(4) 
            if not combination.any(): 
                print(sigmaLabels[i],sigmaLabels[j])
                return

inputDudes = np.kron(X,X)
gate = Cz

# Now I need to isolate the conjugate operator
conjOp = gate.conj().T@inputDudes@gate
gate


array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0., -1.]])

In [161]:
conjOp

array([[ 0.,  0.,  0., -1.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-1.,  0.,  0.,  0.]])

In [162]:
conjugate(conjOp) 

XZ ZX
